// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqTg_VYs2EiSzCtVUTsdoPWTJVltJxy80',
    appId: '1:598347073044:web:213f488d91708edc304901',
    messagingSenderId: '598347073044',
    projectId: 'resumebuilder-a6cc4',
    authDomain: 'resumebuilder-a6cc4.firebaseapp.com',
    storageBucket: 'resumebuilder-a6cc4.appspot.com',
    measurementId: 'G-DVYT3Y1V05',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5twtAzv2ufGuWb-g85V2AxnzuuKKBhd8',
    appId: '1:598347073044:ios:28c84994bc904d60304901',
    messagingSenderId: '598347073044',
    projectId: 'resumebuilder-a6cc4',
    storageBucket: 'resumebuilder-a6cc4.appspot.com',
    iosBundleId: 'com.example.resumeBuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5twtAzv2ufGuWb-g85V2AxnzuuKKBhd8',
    appId: '1:598347073044:ios:28c84994bc904d60304901',
    messagingSenderId: '598347073044',
    projectId: 'resumebuilder-a6cc4',
    storageBucket: 'resumebuilder-a6cc4.appspot.com',
    iosBundleId: 'com.example.resumeBuilder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqTg_VYs2EiSzCtVUTsdoPWTJVltJxy80',
    appId: '1:598347073044:web:f0ff830730e8f7dd304901',
    messagingSenderId: '598347073044',
    projectId: 'resumebuilder-a6cc4',
    authDomain: 'resumebuilder-a6cc4.firebaseapp.com',
    storageBucket: 'resumebuilder-a6cc4.appspot.com',
    measurementId: 'G-B879LM1NRD',
  );
}
